include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = kumquatprefs

kumquatprefs_FILES = KMQRootListController.m
kumquatprefs_FRAMEWORKS = UIKit
kumquatprefs_PRIVATE_FRAMEWORKS = Preferences
kumquatprefs_INSTALL_PATH = /Library/PreferenceBundles
kumquatprefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
